'use client';
import { useEffect, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;
const supabase = createBrowserClient(URL, KEY);

type Screen='home'|'create'|'join'|'prefs'|'room'|'result';
export default function Home(){
 const [screen,setScreen]=useState<Screen>('home'); const [user,setUser]=useState<any>(null); const [email,setEmail]=useState('');
 const [name,setName]=useState(''); const [eventName,setEventName]=useState('Amigo Invisible Fulbito de los Jueves'); const [eventDate,setEventDate]=useState('2026-11-22'); const [code,setCode]=useState(''); const [event,setEvent]=useState<any>(null); const [prefs,setPrefs]=useState(['','','']); const [members,setMembers]=useState<any[]>([]); const [result,setResult]=useState<any>(null); const [msg,setMsg]=useState('');
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return()=>data.subscription.unsubscribe()},[]);
 async function login(){setMsg('Enviando enlace…'); const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}}); setMsg(error?.message??'Revisá tu email para entrar.')}
 async function createEvent(){ if(!user){setMsg('Primero iniciá sesión con tu email.');return} const c=Math.random().toString(36).slice(2,8).toUpperCase(); const {data,error}=await supabase.from('events').insert({name:eventName,gift_type:'Camisetas de fútbol',theme:'fulbito',budget_min:50000,budget_max:100000,event_date:eventDate,organizer_id:user.id,code:c,preference_count:3,detective_mode:true,anonymous_card:true,rules:'Clubes internacionales y selecciones nacionales. No clubes argentinos.'}).select().single(); if(error){setMsg(error.message);return} await supabase.from('event_members').insert({event_id:data.id,user_id:user.id,display_name:name||email.split('@')[0],role:'organizer'}); setEvent(data); setCode(c); await loadMembers(data.id); setScreen('room'); }
 async function join(){if(!user){setMsg('Primero iniciá sesión con tu email.');return} const {data:e,error}=await supabase.from('events').select('*').eq('code',code.trim().toUpperCase()).single(); if(error){setMsg('No encontré ese código.');return} const {error:me}=await supabase.from('event_members').upsert({event_id:e.id,user_id:user.id,display_name:name||email.split('@')[0],role:'participant'},{onConflict:'event_id,user_id'}); if(me){setMsg(me.message);return} setEvent(e); await loadMembers(e.id); setScreen('prefs'); }
 async function savePrefs(){if(!event||!user)return; await supabase.from('preferences').delete().eq('event_id',event.id).eq('user_id',user.id); const rows=prefs.map((value,i)=>({event_id:event.id,user_id:user.id,position:i+1,value:value.trim()})).filter(x=>x.value); if(rows.length!==3){setMsg('Completá las 3 preferencias.');return} const {error}=await supabase.from('preferences').insert(rows); if(error){setMsg(error.message);return} await loadMembers(event.id); setScreen('room'); }
 async function updateEventDate(){if(!event||!user||event.organizer_id!==user.id)return; const {data,error}=await supabase.from('events').update({event_date:eventDate}).eq('id',event.id).eq('organizer_id',user.id).select().single(); if(error){setMsg(error.message);return} setEvent(data); setMsg('Fecha actualizada.')} async function loadMembers(id:string){const {data}=await supabase.from('event_members').select('*').eq('event_id',id).order('joined_at'); setMembers(data||[])}
 async function draw(){if(!event)return; setMsg('Realizando sorteo seguro…'); const {error}=await supabase.rpc('run_secret_draw',{p_event_id:event.id}); if(error){setMsg(error.message);return} setMsg('Sorteo realizado. Tu resultado sigue siendo secreto.'); await loadResult(event.id); await loadMembers(event.id); }
 async function loadResult(id:string){const {data,error}=await supabase.from('assignments').select('recipient_user_id').eq('event_id',id).eq('giver_user_id',user.id).single(); if(error){setMsg(error.message);return} const {data:m}=await supabase.from('event_members').select('display_name').eq('event_id',id).eq('user_id',data.recipient_user_id).single(); const {data:p}=await supabase.from('preferences').select('value').eq('event_id',id).eq('user_id',data.recipient_user_id).order('position'); setResult({name:m?.display_name, prefs:p?.map((x:any)=>x.value)||[]}); setScreen('result'); }
 return <><header><div className="logo">⚽ Amigo Invisible <span>· Fulbito</span></div>{user&&<button className="ghost" onClick={()=>supabase.auth.signOut()}>Salir</button>}</header><main>
 {screen==='home'&&<><section className="hero"><div className="eyebrow">Tu amigo invisible, pero con camiseta</div><h1>Fulbito de los Jueves</h1><p>Organizá el intercambio, hacé el sorteo y mantené el misterio hasta el asado.</p><div className="actions"><button onClick={()=>setScreen('create')}>＋ Crear amigo invisible</button><button className="secondary" onClick={()=>setScreen('join')}>🔑 Unirme a un evento</button></div></section><div className="grid"><Card t="🤫 Sorteo secreto" d="Cada participante ve únicamente a quién debe regalar."/><Card t="🚫 Preferencias" d="Cada uno carga sus 3 equipos o regalos no deseados."/><Card t="📧 Resultado individual" d="La asignación queda protegida para cada participante."/></div></>}
 {screen==='create'&&<Panel title="Crear amigo invisible"><label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellido"/></label><label>Nombre del evento<input value={eventName} onChange={e=>setEventName(e.target.value)}/></label><div className="row"><label>Tipo de regalo<select><option>Camisetas de fútbol</option></select></label><label>Tema visual<select><option>⚽ Fulbito</option></select></label></div><label>Fecha del intercambio<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><div className="row"><label>Presupuesto mínimo<input type="number" value="50000" readOnly/></label><label>Presupuesto máximo<input type="number" value="100000" readOnly/></label></div><div className="actions"><button onClick={createEvent}>Crear evento →</button><button className="secondary" onClick={()=>setScreen('home')}>Volver</button></div></Panel>}
 {screen==='join'&&<Panel title="Unirme a un evento"><label>Código del evento<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Ej: FULBITO"/></label><label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellido"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@email.com"/></label><div className="actions"><button onClick={user?join:login}>{user?'Continuar →':'Recibir acceso por email →'}</button></div></Panel>}
 {screen==='prefs'&&<Panel title="Tus preferencias"><p className="muted">Elegí 3 equipos/selecciones que NO querés recibir.</p>{prefs.map((p,i)=><label key={i}>🚫 No deseado #{i+1}<input value={p} onChange={e=>setPrefs(a=>a.map((x,j)=>j===i?e.target.value:x))} placeholder={i===0?'Ej: Real Madrid':i===1?'Ej: Brasil':'Ej: Manchester United'}/></label>)}<div className="actions"><button onClick={savePrefs}>Guardar preferencias →</button></div></Panel>}
 {screen==='room'&&<Panel title={event?.name||'Evento'}><p className="muted">Código para compartir: <strong>{event?.code}</strong></p><p className="muted">📅 Intercambio: <strong>{event?.event_date ? new Date(event.event_date+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}) : 'Sin fecha'}</strong></p>{event?.organizer_id===user?.id&&<div className="row"><label>Cambiar fecha<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><div className="actions" style={{alignItems:'end'}}><button onClick={updateEventDate}>Guardar fecha</button></div></div>}<div className="card"><div className="topline"><strong>Participantes</strong><span>{members.length}</span></div>{members.map(m=><div className="player" key={m.user_id}><span>⚽ {m.display_name}</span><span className="ok">✓</span></div>)}<div className="actions"><button onClick={draw}>🎲 Realizar sorteo</button>{event?.status==='drawn'&&<button className="secondary" onClick={()=>loadResult(event.id)}>🎁 Ver mi resultado</button>}</div></div><p className="muted small">El organizador no puede consultar los cruces. Cada participante sólo puede leer su propia asignación.</p></Panel>}
 {screen==='result'&&<div className="result"><div className="eyebrow">🎁 TU AMIGO INVISIBLE</div><div className="secret">{result?.name||'—'}</div><p className="muted">Tenés que regalarle una camiseta.</p><div className="grid"><Card t="🚫 No regalar" d={result?.prefs?.join(' · ')||'Sin preferencias'}/><Card t="💰 Presupuesto" d="$50.000 – $100.000"/></div><div className="actions"><button onClick={()=>setScreen('room')}>Volver a mi evento</button></div></div>}
 {msg&&<div className="toast">{msg}</div>}</main><footer>Amigo Invisible · preparado para múltiples eventos y tipos de regalo.</footer></>}
function Card({t,d}:{t:string,d:string}){return <div className="card"><h3>{t}</h3><p className="muted">{d}</p></div>}; function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><div className="topline"><button className="back" onClick={()=>history.back()}>← Volver</button><span className="pill">Fulbito</span></div><h2>{title}</h2>{children}</section>}
