'use client';
import { useEffect, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';

const URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!;
const supabase = createBrowserClient(URL, KEY);

type Screen='home'|'create'|'join'|'prefs'|'room'|'result';
export default function Home(){
 const [screen,setScreen]=useState<Screen>('home'); const [user,setUser]=useState<any>(null); const [email,setEmail]=useState(''); const [authBusy,setAuthBusy]=useState(false);
 const [name,setName]=useState(''); const [eventName,setEventName]=useState('Amigo Invisible Fulbito de los Jueves'); const [eventDate,setEventDate]=useState('2026-11-22'); const [code,setCode]=useState(''); const [event,setEvent]=useState<any>(null); const [prefs,setPrefs]=useState(['','','']); const [members,setMembers]=useState<any[]>([]); const [result,setResult]=useState<any>(null); const [msg,setMsg]=useState('');
 const pendingKey='amigo-invisible-pending-auth';
 useEffect(()=>{
   const pending=localStorage.getItem(pendingKey);
   if(pending){try{const a=JSON.parse(pending); if(a.screen==='create'){setScreen('create'); setName(a.name||''); setEventName(a.eventName||'Amigo Invisible Fulbito de los Jueves'); setEventDate(a.eventDate||'2026-11-22')} if(a.screen==='join'){setScreen('join'); setCode(a.code||''); setName(a.name||''); setEmail(a.email||'')}}catch{localStorage.removeItem(pendingKey)}}
   supabase.auth.getUser().then(({data})=>{setUser(data.user); if(data.user) continueAfterAuth(data.user)});
   const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null); if(s?.user) continueAfterAuth(s.user)});
   return()=>data.subscription.unsubscribe()
 },[]);
 async function continueAfterAuth(authUser:any){
   const raw=localStorage.getItem(pendingKey); if(!raw) return;
   try{const pending=JSON.parse(raw); localStorage.removeItem(pendingKey);
     if(pending.screen==='create'){setScreen('create'); await createEvent(authUser)}
     if(pending.screen==='join'){setScreen('join'); await join(authUser)}
   }catch{localStorage.removeItem(pendingKey)}
 }
 async function login(){
   const clean=email.trim().toLowerCase(); if(!clean){setMsg('Ingresá tu email para continuar.');return}
   const pending=screen==='create'?{screen:'create',name,eventName,eventDate}:{screen:'join',code,name,email:clean};
   localStorage.setItem(pendingKey,JSON.stringify(pending)); setAuthBusy(true); setMsg('Enviando enlace de acceso…');
   const {error}=await supabase.auth.signInWithOtp({email:clean,options:{emailRedirectTo:location.origin}});
   setAuthBusy(false); if(error){localStorage.removeItem(pendingKey); setMsg(error.message);return}
   setMsg('Listo. Revisá tu email y tocá el enlace. Al volver, continuamos automáticamente.');
 }
 async function requireLogin(){setMsg('Ingresá tu email para continuar. Te enviamos un enlace sin contraseña.');}

 async function createEvent(authUser=user){ if(!authUser){setMsg('Ingresá con tu email para crear el evento.');return} const c=Math.random().toString(36).slice(2,8).toUpperCase(); const {data,error}=await supabase.from('events').insert({name:eventName,gift_type:'Camisetas de fútbol',theme:'fulbito',budget_min:50000,budget_max:100000,event_date:eventDate||null,organizer_id:authUser.id,code:c,preference_count:3,detective_mode:true,anonymous_card:true,rules:'Clubes internacionales y selecciones nacionales. No clubes argentinos.'}).select().single(); if(error){setMsg(error.message);return} const {error:memberError}=await supabase.from('event_members').insert({event_id:data.id,user_id:authUser.id,display_name:name||email.split('@')[0],role:'organizer'}); if(memberError){setMsg(memberError.message); return} setEvent(data); setCode(c); await loadMembers(data.id); setScreen('room'); setMsg('Evento creado. Compartí el código con tu grupo.'); }
 async function join(authUser=user){if(!authUser){setMsg('Ingresá con tu email para unirte al evento.');return} const {data:e,error}=await supabase.from('events').select('*').eq('code',code.trim().toUpperCase()).single(); if(error){setMsg('No encontré ese código.');return} const {error:me}=await supabase.from('event_members').upsert({event_id:e.id,user_id:authUser.id,display_name:name||email.split('@')[0],role:'participant'},{onConflict:'event_id,user_id'}); if(me){setMsg(me.message);return} setEvent(e); await loadMembers(e.id); setScreen('prefs'); setMsg('¡Te uniste al evento! Ahora completá tus 3 preferencias.'); }
 async function savePrefs(){if(!event||!user)return; await supabase.from('preferences').delete().eq('event_id',event.id).eq('user_id',user.id); const rows=prefs.map((value,i)=>({event_id:event.id,user_id:user.id,position:i+1,value:value.trim()})).filter(x=>x.value); if(rows.length!==3){setMsg('Completá las 3 preferencias.');return} const {error}=await supabase.from('preferences').insert(rows); if(error){setMsg(error.message);return} await loadMembers(event.id); setScreen('room'); }
 async function loadMembers(id:string){const {data}=await supabase.from('event_members').select('*').eq('event_id',id).order('joined_at'); const list=data||[]; const {data:ps}=await supabase.from('preferences').select('user_id,position').eq('event_id',id); const counts=new Map<string,number>(); (ps||[]).forEach((p:any)=>counts.set(p.user_id,(counts.get(p.user_id)||0)+1)); setMembers(list.map((m:any)=>({...m,preferences_complete:(counts.get(m.user_id)||0)>=3})));}
 async function draw(){if(!event)return; setMsg('Realizando sorteo seguro…'); const {error}=await supabase.rpc('run_secret_draw',{p_event_id:event.id}); if(error){setMsg(error.message);return} setMsg('Sorteo realizado. Tu resultado sigue siendo secreto.'); await loadResult(event.id); await loadMembers(event.id); }
 async function loadResult(id:string){const {data,error}=await supabase.from('assignments').select('recipient_user_id').eq('event_id',id).eq('giver_user_id',user.id).single(); if(error){setMsg(error.message);return} const {data:m}=await supabase.from('event_members').select('display_name').eq('event_id',id).eq('user_id',data.recipient_user_id).single(); const {data:p}=await supabase.from('preferences').select('value').eq('event_id',id).eq('user_id',data.recipient_user_id).order('position'); setResult({name:m?.display_name, prefs:p?.map((x:any)=>x.value)||[]}); setScreen('result'); }
 return <><header><div className="logo">⚽ Amigo Invisible <span>· Fulbito</span></div>{user&&<button className="ghost" onClick={()=>supabase.auth.signOut()}>Salir</button>}</header><main>
 {screen==='home'&&<><section className="hero"><div className="eyebrow">Tu amigo invisible, pero con camiseta</div><h1>Fulbito de los Jueves</h1><p>Organizá el intercambio, hacé el sorteo y mantené el misterio hasta el asado.</p><div className="actions"><button onClick={()=>setScreen('create')}>＋ Crear amigo invisible</button><button className="secondary" onClick={()=>setScreen('join')}>🔑 Unirme a un evento</button></div></section><div className="grid"><Card t="🤫 Sorteo secreto" d="Cada participante ve únicamente a quién debe regalar."/><Card t="🚫 Preferencias" d="Cada uno carga sus 3 equipos o regalos no deseados."/><Card t="📧 Resultado individual" d="La asignación queda protegida para cada participante."/></div></>}
 {screen==='create'&&<Panel title="Crear amigo invisible">{!user&&<div className="authbox"><h3>Ingresá para crear tu evento</h3><p className="muted">Te enviamos un enlace mágico por email. No necesitás contraseña.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@email.com" autoComplete="email"/></label><button onClick={login} disabled={authBusy}>{authBusy?'Enviando…':'📧 Enviar acceso por email'}</button></div>}<label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellido"/></label><label>Nombre del evento<input value={eventName} onChange={e=>setEventName(e.target.value)}/></label><div className="row"><label>Tipo de regalo<select><option>Camisetas de fútbol</option></select></label><label>Tema visual<select><option>⚽ Fulbito</option></select></label></div><div className="row"><label>Presupuesto mínimo<input type="number" value="50000" readOnly/></label><label>Presupuesto máximo<input type="number" value="100000" readOnly/></label></div><label>Fecha de entrega<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><div className="actions"><button onClick={user?createEvent:requireLogin} disabled={authBusy}>{user?'Crear evento →':'Ingresá para crear →'}</button><button className="secondary" onClick={()=>setScreen('home')}>Volver</button></div></Panel>}
 {screen==='join'&&<Panel title="Unirme a un evento"><label>Código del evento<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Ej: FULBITO"/></label><label>Tu nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre y apellido"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@email.com"/></label><div className="actions"><button onClick={user?join:login}>{user?'Continuar →':'Recibir acceso por email →'}</button></div></Panel>}
 {screen==='prefs'&&<Panel title="Tus preferencias"><p className="muted">Elegí 3 equipos/selecciones que NO querés recibir.</p>{prefs.map((p,i)=><label key={i}>🚫 No deseado #{i+1}<input value={p} onChange={e=>setPrefs(a=>a.map((x,j)=>j===i?e.target.value:x))} placeholder={i===0?'Ej: Real Madrid':i===1?'Ej: Brasil':'Ej: Manchester United'}/></label>)}<div className="actions"><button onClick={savePrefs}>Guardar preferencias →</button></div></Panel>}
 {screen==='room'&&<Panel title={event?.name||'Evento'}><p className="muted">Código para compartir: <strong>{event?.code}</strong></p><p className="muted small">📅 Entrega: {event?.event_date||eventDate||'Sin fecha'}</p><div className="card"><div className="topline"><strong>Participantes</strong><span>{members.length}</span></div>{members.map(m=><div className="player" key={m.user_id}><span>⚽ {m.display_name}</span><span className={m.preferences_complete?'ok':'pending'}>{m.preferences_complete?'✓':'Pendiente'}</span></div>)}<div className="actions">{event?.organizer_id===user?.id&&<button onClick={draw} disabled={members.length<2||!members.every(m=>m.preferences_complete)}>🎲 Realizar sorteo</button>}{event?.status==='drawn'&&<button className="secondary" onClick={()=>loadResult(event.id)}>🎁 Ver mi resultado</button>}</div></div><p className="muted small">El organizador no puede consultar los cruces. Cada participante sólo puede leer su propia asignación.</p></Panel>}
 {screen==='result'&&<div className="result"><div className="eyebrow">🎁 TU AMIGO INVISIBLE</div><div className="secret">{result?.name||'—'}</div><p className="muted">Tenés que regalarle una camiseta.</p><div className="grid"><Card t="🚫 No regalar" d={result?.prefs?.join(' · ')||'Sin preferencias'}/><Card t="💰 Presupuesto" d="$50.000 – $100.000"/><Card t="📅 Entrega" d={event?.event_date||eventDate||'Sin fecha'}/></div><div className="actions"><button onClick={()=>setScreen('room')}>Volver a mi evento</button></div></div>}
 {msg&&<div className="toast">{msg}</div>}</main><footer>Amigo Invisible · preparado para múltiples eventos y tipos de regalo.</footer></>}
function Card({t,d}:{t:string,d:string}){return <div className="card"><h3>{t}</h3><p className="muted">{d}</p></div>}; function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><div className="topline"><button className="back" onClick={()=>history.back()}>← Volver</button><span className="pill">Fulbito</span></div><h2>{title}</h2>{children}</section>}
